### ISSUE TITLE
Error compiling the glocal_exploration folder

### ISSUE THREAD

**Issue by yanyifengbupt** [ethz-asl/glocal_exploration#23]
When I executed the command:catkin build glocal_exploration_ros, the following errors appeared. These errors should be from the same problem. I intercepted one of the errors.

/HOME/exploration_map/src/glocal_exploration/glocal_exploration/include/glocal_exploration/3rd_party/config_utilities.hpp:200:39: error: invalid static_cast from type ‘const XmlRpc::XmlRpcValue’ to type ‘bool’
         *param = static_cast<bool>(xml);

Do you know how to solve these problems?

**Comment by zhangzhen886** [comment]
Have you solved this problem?
