### ISSUE TITLE
Voxfield integration

### ISSUE THREAD

**Issue by marcoCella** [ethz-asl/glocal_exploration#37]
Hi!

I’ve been trying to use [Voxfield](https://github.com/VIS4ROB-lab/voxfield) instead of Voxblox as the underlying mapping framework. The issue is that the changes that you implemented in the **glocal/release** branch of Voxblox are quite extensive, so the statement of Voxfield _"Voxfield can be seamlessly integrated into those projects that originally use Voxblox as their volumetric mapping backbone"_ does not hold anymore

Would it be possible to have a GLocal branch that interfaces with Voxfield? And if that would be too much work, could you give me some pointers to the main differences between your Voxblox branch and the main one?

Thanks!

**Comment by Lorenzo-Capaldo** [comment]
Actually I'm having similar compatibility issues

**Comment by marcoCella** [comment]
Fixed it
